Question/Category relations
faire-care-questionnaire/api pull request #13
Opened 2020-10-14 12:42 UTC by Peverse

2020-10-14 13:19 UTC, Robin2807 requested changes

2020-10-14 13:19 UTC, Robin2807 commented on app/models/question.model.js
> -    },
category_id is weggehaald omdat je hem hebt veranderd naar categoryId denk ik? Kan het dan zijn dat je hier nog wel een categoryId moet toevoegen, want nu als ik npm start doe maakt hij geen kolom aan voor de category id.

2020-10-15 07:15 UTC, Robin2807 approved these changes

2020-10-15 07:32 UTC, nathanaelbaaij approved these changes
Ziet er goed uit

2020-10-15 07:33 UTC, merged