Input types crud
faire-care-questionnaire/api pull request #8
Opened 2020-10-13 11:54 UTC by Robin2807

2020-10-13 13:02 UTC, Peverse approved these changes
Niks op aan te merken.

2020-10-14 07:28 UTC, nathanaelbaaij requested changes
Ziet er goed uit, enkel even kijken naar NODE_ENV='test'

2020-10-14 07:28 UTC, nathanaelbaaij commented on package.json
> -    "test": "NODE_ENV=test jest --forceExit --detectOpenHandles  --watchAll"
NODE_ENV=test zou ik erin laten omdat je dan aangeeft dat je tijdens het testen aangeeft dat de app in test modus zit.

2020-10-14 07:32 UTC, nathanaelbaaij approved these changes

2020-10-14 07:32 UTC, merged